postgresql:
  host: localhost
  port: 5432
  user: postgres
  password: ssss
  dbname: awesome-eval
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

rabbitmq:
  host: localhost
  port: 5672
  user: admin
  password: admin
  vhost: /

minio:
  endpoint: localhost:9000
  accessKeyID: minioadmin
  secretAccessKey: minioadmin
  useSSL: false
  bucketName: my-bucket

log:
  encoding: json
  outputPaths:
    - stdout
    - ./logs/app.log
  errorOutputPaths:
    - stderr
  development: true
