postgresql:
  host: localhost
  port: 5432
  user: postgres
  password: ssss
  dbname: awesome-eval
  sslmode: disable

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

rabbitmq:
  host: localhost
  port: 5672
  user: admin
  password: admin
  vhost: / 